# This file stores qualitative, non-API data for each exchange.
# Data can be manually updated here.
# Supported fields:
#   security_measures, customer_service, platform_stability, fund_insurance,
#   regional_restrictions, withdrawal_limits, withdrawal_speed,
#   supported_cross_chain_bridges, api_support_details, fee_discounts,
#   margin_leverage_details, maintenance_schedule, user_rating_summary,
#   tax_compliance_info, deposit_networks, deposit_fees, withdrawal_networks,
#   margin_trading_api

binance:
  security_measures: "行业领先的安全性，SAFU基金。"
  customer_service: "7x24小时支持，通常响应迅速。"
  platform_stability: "高，但在极端波动期间可能会遇到问题。"
  fund_insurance: "SAFU（用户安全资产基金）提供保护。"
  regional_restrictions: "在某些地区不可用，包括美国（使用Binance.US）。"
  withdrawal_limits: "因KYC级别而异。标准限额很高。"
  withdrawal_speed: "通常很快，取决于网络拥堵情况（例如5-60分钟）。"
  supported_cross_chain_bridges: "支持BSC桥，以及在多个链上直接存款/取款。"
  api_support_details: "全面的REST和WebSocket API。文档齐全。"
  fee_discounts: "是，通过持有BNB代币或通过特定促销活动。"
  margin_leverage_details: "提供高杠杆的保证金交易和期货。"
  maintenance_schedule: "提前宣布，通常在低流量时段。"
  user_rating_summary: "功能评分高，但可能会有支持方面的投诉。"
  tax_compliance_info: "为税务目的提供交易历史导出功能。"
  deposit_networks: "BTC, ETH (ERC20), BSC (BEP20), TRON (TRC20), etc."
  deposit_fees: "通常免费。"
  withdrawal_networks: "BTC, ETH (ERC20), BSC (BEP20), TRON (TRC20), etc."
  margin_trading_api: "是，通过统一的交易API提供。"

okx:
  security_measures: "储备金证明，冷存储，风险管理系统。"
  customer_service: "良好，有多个渠道可用。"
  platform_stability: "通常稳定可靠。"
  fund_insurance: "持有大量储备金。"
  regional_restrictions: "在美国和其他司法管辖区有限制。"
  withdrawal_limits: "根据KYC验证分级。"
  withdrawal_speed: "通常在30分钟内处理。"
  supported_cross_chain_bridges: "支持多个原生链，减少了桥接需求。"
  api_support_details: "功能齐全的交易和数据API。"
  fee_discounts: "是，根据OKB代币持有量和交易量。"
  margin_leverage_details: "广泛的保证金和衍生品交易选项。"
  maintenance_schedule: "定期的、预先宣布的维护窗口。"
  user_rating_summary: "因其广泛的功能而备受推崇。"
  tax_compliance_info: "提供交易历史导出工具。"
  deposit_networks: "BTC, ETH (ERC20), OKTC, TRON (TRC20), etc."
  deposit_fees: "免费。"
  withdrawal_networks: "BTC, ETH (ERC20), OKTC, TRON (TRC20), etc."
  margin_trading_api: "是，包含在主API中。"

bybit:
  security_measures: "多重签名冷钱包，强大的安全审计。"
  customer_service: "以响应迅速的7x24小时客户支持而闻名。"
  platform_stability: "高性能撮合引擎，非常稳定。"
  fund_insurance: "用于弥补合约损失的保险基金。"
  regional_restrictions: "在美国、英国和其他地区有服务限制。"
  withdrawal_limits: "取决于KYC级别，对已验证用户通常很高。"
  withdrawal_speed: "非常快，通常在15分钟内处理完毕。"
  supported_cross_chain_bridges: "主要依赖于直接的多链支持。"
  api_support_details: "高性能API，受机器人和自动交易者欢迎。"
  fee_discounts: "通过各种促销计划提供。"
  margin_leverage_details: "专注于衍生品和杠杆交易。"
  maintenance_schedule: "停机时间最短，升级会提前宣布。"
  user_rating_summary: "在性能和衍生品方面评价极高。"
  tax_compliance_info: "提供标准交易历史记录。"
  deposit_networks: "ETH (ERC20), BSC (BEP20), Arbitrum, etc."
  deposit_fees: "免费。"
  withdrawal_networks: "ETH (ERC20), BSC (BEP20), Arbitrum, etc."
  margin_trading_api: "是，是其API产品的核心部分。"

kucoin:
  security_measures: "银行级资产安全，定期审计。"
  customer_service: "提供支持，但响应时间可能有所不同。"
  platform_stability: "良好，但过去曾面临性能问题。"
  fund_insurance: "针对系统相关损失的保险基金。"
  regional_restrictions: "广泛可用，但在美国等某些地区有服务限制。"
  withdrawal_limits: "标准限额，通过KYC增加。"
  withdrawal_speed: "可变，可能很快，但有时会有延迟。"
  supported_cross_chain_bridges: "对多链有良好支持。"
  api_support_details: "提供广泛的API端点。"
  fee_discounts: "是，通过持有KCS代币。"
  margin_leverage_details: "提供保证金、期货和交易机器人。"
  maintenance_schedule: "提前宣布。"
  user_rating_summary: "因其大量的山寨币选择而被称为“人民的交易所”。"
  tax_compliance_info: "交易历史可供下载。"
  deposit_networks: "BTC, ETH (ERC20), KCC, TRON (TRC20), etc."
  deposit_fees: "免费。"
  withdrawal_networks: "BTC, ETH (ERC20), KCC, TRON (TRC20), etc."
  margin_trading_api: "是。"

gate:
  security_measures: "储备金证明，漏洞赏金计划。"
  customer_service: "多个支持渠道，响应速度一般。"
  platform_stability: "稳定，拥有非常广泛的上市资产。"
  fund_insurance: "没有具体的、公开详细的保险基金。"
  regional_restrictions: "在美国和其他一些国家不可用。"
  withdrawal_limits: "标准的分级提款限额。"
  withdrawal_speed: "通常很快，但可能会有所不同。"
  supported_cross_chain_bridges: "优秀的多链支持。"
  api_support_details: "功能性API，但文档可能不如竞争对手详细。"
  fee_discounts: "是，根据GT代币持有量和VIP等级。"
  margin_leverage_details: "提供广泛的保证金交易对。"
  maintenance_schedule: "定期安排。"
  user_rating_summary: "因资产种类繁多而受到称赞，因复杂性而受到批评。"
  tax_compliance_info: "标准导出功能。"
  deposit_networks: "多样的，几乎支持所有上市资产的原生链。"
  deposit_fees: "免费。"
  withdrawal_networks: "多样的，几乎支持所有上市资产的原生链。"
  margin_trading_api: "是。"

mexc:
  security_measures: "先进的风险控制系统，冷存储。"
  customer_service: "7x24小时支持，质量可能不一致。"
  platform_stability: "总体良好，专注于海量资产。"
  fund_insurance: "持有用户资金储备，细节未具体说明。"
  regional_restrictions: "在许多地区可用，但在美国受限。"
  withdrawal_limits: "标准的基于KYC的限额。"
  withdrawal_speed: "平均，通常在一小时内。"
  supported_cross_chain_bridges: "直接支持大量链。"
  api_support_details: "提供标准API。"
  fee_discounts: "是，通过持有MX代币。"
  margin_leverage_details: "提供杠杆ETF和期货。"
  maintenance_schedule: "根据需要，通过官方渠道宣布。"
  user_rating_summary: "因在新山寨币中寻找“宝石”的机会而受欢迎。"
  tax_compliance_info: "提供交易记录。"
  deposit_networks: "ETH (ERC20), BSC (BEP20), TRON (TRC20), etc."
  deposit_fees: "免费。"
  withdrawal_networks: "ETH (ERC20), BSC (BEP20), TRON (TRC20), etc."
  margin_trading_api: "是。"

bitget:
  security_measures: "储备金证明，保护基金。"
  customer_service: "活跃的客户支持，尤其是在社交渠道。"
  platform_stability: "良好，以跟单交易功能闻名。"
  fund_insurance: "保护基金以保障用户资产。"
  regional_restrictions: "在美国和其他主要市场受限。"
  withdrawal_limits: "基于KYC的标准限额。"
  withdrawal_speed: "快速可靠。"
  supported_cross_chain_bridges: "良好的多链支持。"
  api_support_details: "强大的API支持，尤其适用于跟单交易。"
  fee_discounts: "是，通过持有BGB代币。"
  margin_leverage_details: "专注于跟单交易、期货和保证金。"
  maintenance_schedule: "预先宣布的维护。"
  user_rating_summary: "因其社交/跟单交易功能而获得高度评价。"
  tax_compliance_info: "标准交易历史导出。"
  deposit_networks: "ETH (ERC20), BSC (BEP20), TRON (TRC20), etc."
  deposit_fees: "免费。"
  withdrawal_networks: "ETH (ERC20), BSC (BEP20), TRON (TRC20), etc."
  margin_trading_api: "是。"

htx:
  security_measures: "储备金证明，安全储备基金。"
  customer_service: "7x24小时支持。"
  platform_stability: "运营时间长的交易所，通常稳定。"
  fund_insurance: "20,000 BTC安全储备基金。"
  regional_restrictions: "在美国不可用。"
  withdrawal_limits: "标准的分级限额。"
  withdrawal_speed: "平均处理时间。"
  supported_cross_chain_bridges: "支持Heco链和其他主要网络。"
  api_support_details: "成熟稳定的API。"
  fee_discounts: "是，通过持有HT代币。"
  margin_leverage_details: "提供全套的保证金和衍生产品。"
  maintenance_schedule: "定期安排的维护。"
  user_rating_summary: "一家历史悠久、声誉卓著的老牌交易所。"
  tax_compliance_info: "为用户提供必要的交易数据。"
  deposit_networks: "ETH (ERC20), HECO, TRON (TRC20), etc."
  deposit_fees: "免费。"
  withdrawal_networks: "ETH (ERC20), HECO, TRON (TRC20), etc."
  margin_trading_api: "是。"
